CONFIG_ZMK_USB_LOGGING=n
CONFIG_ZMK_POINTING_DEVICE=y
CONFIG_ZMK_MOUSE=y
CONFIG_ZMK_MOUSE_KEYCODE=y


# Movement speed settings
CONFIG_ZMK_MOUSE_MOVE_INTERVAL=8       # Lower = faster repeat
CONFIG_ZMK_MOUSE_MOVE_MAX_SPEED=10     # Higher = faster cursor

# Scroll speed settings
CONFIG_ZMK_MOUSE_SCROLL_INTERVAL=8
CONFIG_ZMK_MOUSE_SCROLL_MAX_SPEED=6
