manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: b54b0fa0389a9108c35398cc9e59d57a9cfd758f
      import: app/west.yml
  self:
    path: config
